src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Start_Date__c</fullName>
        <label>Client Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If client - check box</inlineHelpText>
        <label>Client</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Use this Record Type for Client Accounts.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_Start_Date__c</fullName>
        <label>Client Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Leg__c.object
<CustomObject>
    <description>This is used for flight legs.</description>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Client)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Departure_Date__c</fullName>
        <inlineHelpText>Local departure date</inlineHelpText>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Status__c</fullName>
        <label>Flight Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Brutal Recovery – Flew Commercial</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
                <value>
                    <fullName>Departed</fullName>
                </value>
                <value>
                    <fullName>Flown</fullName>
                </value>
                <value>
                    <fullName>Imported</fullName>
                </value>
                <value>
                    <fullName>In Review - Alana</fullName>
                </value>
                <value>
                    <fullName>In Review - Amy</fullName>
                </value>
                <value>
                    <fullName>In Review - Andrew</fullName>
                </value>
                <value>
                    <fullName>In Review - Bill</fullName>
                </value>
                <value>
                    <fullName>In Review - Craig</fullName>
                </value>
                <value>
                    <fullName>In Review - Jaime</fullName>
                </value>
                <value>
                    <fullName>In Review - Jeff</fullName>
                </value>
                <value>
                    <fullName>In Review - Luke</fullName>
                </value>
                <value>
                    <fullName>In Review - Mark</fullName>
                </value>
                <value>
                    <fullName>In Review - Needs Assignment</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Special</fullName>
                </value>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Vendor Could Cover Flight - Violation</fullName>
                    <label>Vendor Could Not Cover Flight - Violation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Passenger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Passenger</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Legs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leg_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Leg Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leg_Sequence_Number__c</fullName>
        <inlineHelpText>Leg Sequence Number (e.g., 1, 2, 3, 4, 5).</inlineHelpText>
        <label>Leg Sequence #</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution_Category__c</fullName>
        <formula>TEXT( Itinerary_Solution_Number__r.Solution_Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Category</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Entire_Agreement_End_Date__c</fullName>
        <label>Entire Agreement End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quarterly_Summary__c.object
<CustomObject>
    <fields>
        <fullName>AvP_Relationship_Improvement_Areas__c</fullName>
        <label>AvP Relationship Improvement Areas</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Aviation_Portfolio_Relationship_Status__c</fullName>
        <label>Aviation Portfolio Relationship Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quarterly Summaries</relationshipLabel>
        <relationshipName>Quarterly_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Areas_of_AvP_Focus__c</fullName>
        <label>Main Areas of AvP Focus</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Main_Areas_of_AvP_Impact_to_Client__c</fullName>
        <label>Main Areas of AvP Impact to Client</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portfolio_Optimization_Opportunities__c</fullName>
        <label>Portfolio Optimization Opportunities</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portfolio_Optimization_Successes__c</fullName>
        <label>Portfolio Optimization Successes</label>
        <type>TextArea</type>
    </fields>
    <label>Quarterly Summary</label>
    <nameField>
        <displayFormat>QS-{00}</displayFormat>
        <label>Quarterly Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quarterly Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
public with sharing class TestDataFactory {

	public static list<Profile> fetchProfile(String strProfile){
		UserLicense objUserLicense = [SELECT Id 
                         FROM UserLicense 
                         where Name ='Customer Community Plus' limit 1];
		list<Profile>lstProfile = [SELECT Id,
		                                  UserLicenseId 
                                     FROM Profile 
                                     where UserLicenseId=: objUserLicense.Id
                                     limit 1];
		return lstProfile;
	}//End of fetchProfile
	
	public static list<user> CreateUser(Integer intCounter,Id profileId ,Id contactId){
		list<User> newUserList = new list<User>();
        for(Integer i=0 ; i<intCounter ; i++){
            User tempUser = new User();
            tempUser.Alias = 'standt';
            tempUser.Email='standarduser@testorg.com'; 
            tempUser.EmailEncodingKey='UTF-8'; 
            tempUser.LastName='Testing'; 
            tempUser.LanguageLocaleKey='en_US'; 
            tempUser.LocaleSidKey='en_US';
            tempUser.ProfileId = profileId;
            tempUser.UserName='standarduser7402267@testorg.com'+intCounter;
            tempUser.Division = 'Corporate';
            tempUser.TimeZoneSidKey='America/Los_Angeles';
            tempUser.ContactId = contactId;
            newUserList.add(tempUser);
        }
        return newUserList;
	}//End of CreateUser
	
	public static list<Account> CreateAccount(Integer intCounter,String strName){
		list<account>lstAccount = new list<Account>();
		for(Integer i=0 ; i<IntCounter ; i++){
			Account objAccount = new Account();
			objAccount.name = strName + i;
			lstAccount.add(objAccount);
		}
		return lstAccount; 
	}//End of CreateAccount
	
	public static list<Contact> CreateContact(Integer intCounter,String strLastName,String StrAccId){
		list<Contact>lstContact = new list<Contact>();
		for(Integer i=0 ; i<IntCounter ; i++){
			Contact objContact = new Contact();
			objContact.LastName = strLastName + i;
			objContact.AccountId = StrAccId;
			objContact.Client_Start_Date__c= date.today();
			lstContact.add(objContact);
		}
		return lstContact;
	}//End of CreateContact
	
	public static list<Opportunity> createOpportunity(Integer intCounter,String OppName,String StrAccId){
		list<Opportunity>lstOpportunity = new list<Opportunity>();
		for(Integer i=0 ; i<IntCounter ; i++){
			Opportunity objOpportunity  = new Opportunity();
			objOpportunity.Name = OppName + i;
			objOpportunity.CloseDate = date.Today();
			objOpportunity.Amount = 10000+i;
			objOpportunity.StageName = 'Closed Won';
			objOpportunity.AccountId= StrAccId;
			objOpportunity.Entire_Agreement_End_Date__c = date.today().addYears(1);
			lstOpportunity.add(objOpportunity);	            
		}
		return lstOpportunity;
	}//End of createOpportunity
	
	public static list<Quarterly_Summary__c> createQuarterlySummary(Integer intCounter,Id AccountId){
		list<Quarterly_Summary__c>lstQuarterSummary = new list<Quarterly_Summary__c>();
		for(Integer i=0 ; i<IntCounter ; i++){
			Quarterly_Summary__c objQuarterlySummary = new Quarterly_Summary__c();
			objQuarterlySummary.Client__c = AccountId;
			objQuarterlySummary.Aviation_Portfolio_Relationship_Status__c = 'Aviation Portfolio Relationship Status Test'+i;
			objQuarterlySummary.AvP_Relationship_Improvement_Areas__c = 'AvP Relationship Improvement Areas Test'+i;
			objQuarterlySummary.Main_Areas_of_AvP_Focus__c ='Main Areas of AvP Focus Test'; 
			objQuarterlySummary.Main_Areas_of_AvP_Impact_to_Client__c = 'Main Areas of AvP Impact to Client Test'+i;
			objQuarterlySummary.Portfolio_Optimization_Opportunities__c = 'Portfolio Optimization Opportunities Test'+i;
			objQuarterlySummary.Portfolio_Optimization_Successes__c = 'Portfolio Optimization Successes'+i;
			lstQuarterSummary.add(objQuarterlySummary);
		}
		return lstQuarterSummary;
	}//End of createQuarterlySummary
	
	public static list<Leg__c> createLeg(Integer intCounter,String strFliStatus,Id ContactId,integer intLegSequence,Id OwnerId){
		list<Leg__c>lstLeg = new list<Leg__c>();
		for(Integer i=0 ; i<IntCounter ; i++){
			Leg__c objLeg = new Leg__c();
			objLeg.Flight_Status__c = strFliStatus;
			objLeg.Lead_Passenger__c = ContactId;
			objLeg.Leg_Sequence_Number__c = intLegSequence;
			objLeg.Leg_Owner__c = OwnerId;
			objLeg.Departure_Date__c = date.today();
			//objLeg.Solution_Category__c = 
			lstLeg.add(objLeg);
		}
		return lstLeg;
	}  
}//End of TestDataFactory