src/objects/Airport__c.object
<CustomObject>
    <fields>
        <fullName>Airport_Name__c</fullName>
        <label>Airport Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Airport</label>
    <nameField>
        <label>Airport Code (ICAO Code)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trip Managers</relationshipLabel>
        <relationshipName>Trip_Managers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arriving_Airport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Arriving Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Trips (Arriving Airport)</relationshipLabel>
        <relationshipName>Trips1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Requested__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Trip__c</fullName>
        <label>Date of Trip</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departing_Airport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Departing Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Trips (Departing Airport)</relationshipLabel>
        <relationshipName>Trips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domestic_or_International__c</fullName>
        <label>Domestic or International</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose_of_Trip__c</fullName>
        <label>Purpose of Trip</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Business &amp; Personal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trip_Type__c</fullName>
        <label>Trip Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Way</fullName>
                </value>
                <value>
                    <fullName>Round Trip</fullName>
                </value>
                <value>
                    <fullName>Same-Day Round Trip</fullName>
                </value>
                <value>
                    <fullName>Multi-Segment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program_Status__c</fullName>
        <label>Client Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <inlineHelpText>Operator|Annual Hours|Aircraft Type|Product Type (Share/Lease/Card)</inlineHelpText>
        <label>Program Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Year__c.object
<CustomObject>
    <fields>
        <fullName>Client_Program__c</fullName>
        <label>Client Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipName>Client_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Program Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Value_Proposition_del__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Value Propositions</relationshipLabel>
        <relationshipName>Client_Value_Propositions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CVP_Savings__c</fullName>
        <label>CVP Savings $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Client Value Proposition</label>
    <nameField>
        <displayFormat>CVP-{000000}</displayFormat>
        <label>CVP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Value Propositions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Send_Authorization_Form_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Send Authorization Form to</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Send Authorization Form to)</relationshipLabel>
        <relationshipName>Opportunities4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quarterly_Summary__c.object
<CustomObject>
    <label>Quarterly Summary</label>
    <nameField>
        <displayFormat>QS-{00}</displayFormat>
        <label>Quarterly Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quarterly Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaskRay_Task__c</fullName>
        <label>TaskRay Task</label>
        <referenceTo>TASKRAY__Project_Task__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>{MM}-{DD}-{YYYY}-{0}</displayFormat>
        <label>Time Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAviationPageController.cls
@istest
public with sharing class TestAviationPageController {

    static testMethod void validateTestAviationPageController(){

        list<Account>lstAccount = TestDataFactory.CreateAccount(1,'TestAccount');
        insert lstAccount;

        list<Contact>lstContact = TestDataFactory.CreateContact(1,'TestContact', lstAccount[0].id);
        insert lstContact;

        UserLicense objUserLicense = [SELECT Id 
                         FROM UserLicense 
                         where Name ='Customer Community Plus' limit 1];
        list<Profile>lstProfile = [SELECT Id,
                                          UserLicenseId 
                                     FROM Profile 
                                     where UserLicenseId=: objUserLicense.Id
                                     limit 1];
        list<Profile>lstProfileAdmin = [SELECT Id,
                                          UserLicenseId 
                                     FROM Profile 
                                     where Name='System Administrator'
                                     limit 1];
        list<User>lstUser = TestDataFactory.CreateUser(1, lstProfile[0].id, lstContact[0].id);
        insert lstUser;
        User objUser= [select id from User where ProfileId=:lstProfileAdmin[0].Id limit 1];

        list<Opportunity>lstOpportunity = TestDataFactory.createOpportunity(1,'TestOpportunity',lstAccount[0].Id);
        lstOpportunity[0].Send_Authorization_Form_to__c = lstContact[0].Id;
        insert lstOpportunity;

        list<Quarterly_Summary__c>lstQuarterlySumm = TestDataFactory.createQuarterlySummary(1, lstAccount[0].id);
        insert lstQuarterlySumm;

        TASKRAY__Project_Task__c objTaskRay = new TASKRAY__Project_Task__c();
        objTaskRay.Name= 'Test';
        insert objTaskRay;
 
        list<Time__c> lstTime = new list<Time__c>();
        Time__c objTime = new Time__c();
        objTime.Account__c = lstAccount[0].Id;
        objTime.Hours__c = 0.25;
        objTime.Date__c= date.today();
        objTime.TaskRay_Task__c=objTaskRay.Id;
        lstTime.add(objTime);

        Time__c objTime1 = new Time__c();
        objTime1.Account__c = lstAccount[0].Id;
        objTime1.Hours__c = 0.75;
        objTime1.Date__c= date.today();
        objTime1.TaskRay_Task__c=objTaskRay.Id;
        lstTime.add(objTime1);
        insert lstTime;

        Client_Value_Proposition_del__c objValue= new Client_Value_Proposition_del__c();
        objValue.Account__c = lstAccount[0].Id;
        objValue.CVP_Savings__c= 400;
        insert objValue;

        System.runAs(lstUser[0]){
            AviationHomePageController objAviationHomePageController = new AviationHomePageController();    
        system.assertEquals(1, objAviationHomePageController.dblAccHours);
        }                
        //System.runAs( lstUser[0] );
    }// end method

    // method to test the data for flown and Dollar table for current year
    static testMethod void validateDollarFlownData(){
        list<Account>lstAccount = TestDataFactory.CreateAccount(1,'TestAccount');
        insert lstAccount;
        
        list<Contact>lstContact = TestDataFactory.CreateContact(1,'TestContact', lstAccount[0].id);
        insert lstContact;
        
        UserLicense objUserLicense = [SELECT Id 
                         FROM UserLicense 
                         where Name ='Customer Community Plus' limit 1];
        list<Profile>lstProfile = [SELECT Id,
                                          UserLicenseId 
                                     FROM Profile 
                                     where UserLicenseId=: objUserLicense.Id
                                     limit 1];
        list<Profile>lstProfileAdmin = [SELECT Id,
                                          UserLicenseId 
                                     FROM Profile 
                                     where Name='System Administrator'
                                     limit 1];
        list<User>lstUser = TestDataFactory.CreateUser(1, lstProfile[0].id, lstContact[0].id);
        insert lstUser;
        Operator_Program__c objOpProgram= new Operator_Program__c();
        objOpProgram.Operator__c =lstAccount[0].Id;
        objOpProgram.Name='This is test';
        objOpProgram.Program_Status__c = 'Available';
        insert objOpProgram;
        
        User objUser= [select id from User where ProfileId=:lstProfileAdmin[0].Id limit 1];
        
        Client_Program__c objProgram= new Client_Program__c();
        objProgram.Name='Contract 1';
        objProgram.Program_Name__c='Program 1';
        objProgram.Account__c= lstAccount[0].Id;
        objProgram.Operator_Program__c=objOpProgram.Id;
        objProgram.Client_Program_Status__c = 'Active';
        insert objProgram;
        
        Airport__c objAirport = new Airport__c();
        objAirport.Name='ICOO';
        objAirport.Airport_Name__c='International';
        insert objAirport;

        Airport__c objAirport1 = new Airport__c();
        objAirport1.Name='SST';
        objAirport1.Airport_Name__c='International';
        insert objAirport1;

        Case objCase =new Case();
        objCase.Status= 'Booked';
        objCase.AccountId=  lstAccount[0].Id;
        objCase.ContactId=lstContact[0].Id;
        objCase.Origin='Email';
        objCase.Date_Requested__c= date.today();
        objCase.Trip_Type__c='One-Way';
        objCase.Domestic_or_International__c='International';
        objCase.SuppliedName='test';
        objCase.Date_of_Trip__c= date.today();
        objCase.Purpose_of_Trip__c='Business';
        objCase.Departing_Airport__c= objAirport1.Id;
        objCase.Arriving_Airport__c= objAirport1.Id;
        objCase.Description= 'Itinerary/Dates/Routing/Times';
        objCase.Subject='test';
        insert objCase;

        Client_Program_Year__c objYear = new Client_Program_Year__c();
        objYear.Client_Program__c = objProgram.Id;
        insert objYear;

         System.runAs(lstUser[0]){
            AviationHomePageController objAviationHomePageController = new AviationHomePageController();    
            system.assertEquals(1, objAviationHomePageController.setPrName.size());
        }    
    }// end method
}// end class