src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Type_Requested__c</fullName>
        <label>Aircraft Type Requested</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Light Cabin Jet</fullName>
                </value>
                <value>
                    <fullName>Midsize Cabin Jet</fullName>
                </value>
                <value>
                    <fullName>Super-Mid Cabin Jet</fullName>
                </value>
                <value>
                    <fullName>Large Cabin Jet</fullName>
                </value>
                <value>
                    <fullName>Turboprop Aircraft</fullName>
                </value>
                <value>
                    <fullName>Helicopter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commercial_Flight_Details__c</fullName>
        <inlineHelpText>Please provide details regarding the connecting Commercial Flight.</inlineHelpText>
        <label>Commercial Flight Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connecting_To_From_Commercial_Flight__c</fullName>
        <label>Connecting To/From Commercial Flight</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Requested__c</fullName>
        <label>Date Requested</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Budget__c</fullName>
        <label>Flight Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_of_Passengers__c</fullName>
        <label>Potential Max # of Seats Required?</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Non_Stop_Required__c</fullName>
        <label>Non-Stop Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose_of_Trip__c</fullName>
        <label>Purpose of Trip</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Business &amp; Personal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose_of_Trip_if_Other__c</fullName>
        <inlineHelpText>You must populate a Purpose of Trip, if Other is selected.</inlineHelpText>
        <label>Purpose of Trip, if Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Luggage__c</fullName>
        <label>Special Luggage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Trip_Request_Notes__c</fullName>
        <label>Special Trip Request Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Sensitive_Event_Description__c</fullName>
        <inlineHelpText>Please provide details of your time sensitive event.</inlineHelpText>
        <label>Time Sensitive Event Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_to_a_Time_Sensitive_Event__c</fullName>
        <label>Travel to/from a Time Sensitive Event?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trip_Type__c</fullName>
        <label>Trip Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Way</fullName>
                </value>
                <value>
                    <fullName>Round Trip</fullName>
                </value>
                <value>
                    <fullName>Same-Day Round Trip</fullName>
                </value>
                <value>
                    <fullName>Multi-Segment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WiFi_Required__c</fullName>
        <label>WiFi Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Adult_Passengers__c</fullName>
        <label># of Adult Passengers</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Child_Passengers__c</fullName>
        <label># of Child Passengers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Lap_Babies__c</fullName>
        <label># of Babies Under 24 Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Pets__c</fullName>
        <label># of Potential Pets Traveling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TripManagerCtlr.cls
public with sharing class TripManagerCtlr {
    
    ApexPages.StandardController controller;    
    public Date dReq { get { return Date.today(); } set;}
    public String  subj {get;set;}
    public String  des {get;set;}
    public String  timeSensitive {get;set;}
    public Integer  flihtBdgt {get;set;}
    public Integer  maxPass {get;set;}
    public Integer  adltPass {get;set;}
    public Integer  chldPass     {get;set;}
    public Integer  lapBabies {get;set;}
    public Integer  pets {get;set;}
    public String  spclLugg {get;set;}
    public String  spclTripNotes {get;set;}
    public String  cFlightDetails {get;set;}
    public String trTypes {get;set;}
    public String arTypes {get;set;}
    public String nonStopReq {get;set;}
    public String wifiReq {get;set;}
    public String pTrip {get;set;}
    public String travelTime {get;set;}
    public String ccFlight {get;set;}
    public String pTripOthr {get;set;}
    public Case c ;
    PageReference pageRef;

    public TripManagerCtlr(ApexPages.StandardController con){
         controller = con;
    } 
    
    public PageReference saveRecord() {

        try{
            c = new Case();
            c.Date_Requested__c = dReq;
            c.Subject = subj;
            c.Description = des;
            c.Time_Sensitive_Event_Description__c = timeSensitive;
            c.Flight_Budget__c = flihtBdgt;
            c.Max_of_Passengers__c = maxPass;
            c.of_Adult_Passengers__c = adltPass;
            c.of_Child_Passengers__c = chldPass;
            c.of_Lap_Babies__c = lapBabies;
            c.of_Pets__c = pets;
            c.Special_Luggage__c = spclLugg;
            c.Special_Trip_Request_Notes__c = spclTripNotes;
            c.Commercial_Flight_Details__c = cFlightDetails;
            if(trTypes == 'None')
               c.Trip_Type__c = ' ';
            else
               c.Trip_Type__c = trTypes;
            if(arTypes == 'None')
               c.Aircraft_Type_Requested__c = ' '; 
            else     
               c.Aircraft_Type_Requested__c=arTypes;
            if(nonStopReq == 'None')
               c.Non_Stop_Required__c = ' '; 
            else   
               c.Non_Stop_Required__c =nonStopReq;
            if(wifiReq == 'None')
               c.WiFi_Required__c = ' '; 
            else    
               c.WiFi_Required__c = wifiReq;
            if(pTrip == 'None')
               c.Purpose_of_Trip__c = ' '; 
            else     
               c.Purpose_of_Trip__c = pTrip;
            //if(pTrip == 'Other')
              c.Purpose_of_Trip_if_Other__c = pTripOthr;

            if(travelTime == 'None')
               c.Travel_to_a_Time_Sensitive_Event__c = ' '; 
            else    
               c.Travel_to_a_Time_Sensitive_Event__c =travelTime;
            if(ccFlight == 'None')
               c.Connecting_To_From_Commercial_Flight__c = ' '; 
            else    
               c.Connecting_To_From_Commercial_Flight__c = ccFlight;
            insert c;
        }
        catch(Exception e){         

            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage());
            ApexPages.addMessage(errMsg);           
            return null;
        }       

       pageRef = new PageReference('/500/o');
       pageRef.setRedirect(true);
       return pageRef;
    }
    public List<SelectOption> getTripTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Trip_Type__c.getDescribe();       
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));   
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }


    public List<SelectOption> getAirTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Aircraft_Type_Requested__c.getDescribe();         
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    public List<SelectOption> getNonStopReqTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Non_Stop_Required__c.getDescribe();       
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    public List<SelectOption> getWifiReqTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.WiFi_Required__c.getDescribe();       
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    public List<SelectOption> getPTripTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Purpose_of_Trip__c.getDescribe();         
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    public List<SelectOption> getTravelTimeTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Travel_to_a_Time_Sensitive_Event__c.getDescribe();        
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    public List<SelectOption> getCCFlightTypes() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult fieldResult = Case.Connecting_To_From_Commercial_Flight__c.getDescribe();        
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('None','--None--'));
       
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

}