src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trip Managers</relationshipLabel>
        <relationshipName>Trip_Managers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Program</relationshipLabel>
        <relationshipName>CO_Client_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program_Status__c</fullName>
        <label>Client Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contracted_Aircraft_Type__c</fullName>
        <label>Contracted Aircraft Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_MMF__c</fullName>
        <inlineHelpText>Grabbing the MMF from the last reconciled MMF transaction</inlineHelpText>
        <label>Current MMF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_OHF__c</fullName>
        <inlineHelpText>Grabbing the OHF from the latest reconciled leg that was not an up/downgrade</inlineHelpText>
        <label>Current OHF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Latest_Fuel__c</fullName>
        <inlineHelpText>Grabbing latest fuel from latest reconciled transaction that was not up/downgraded</inlineHelpText>
        <label>Latest Fuel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Lease_Fee__c</fullName>
        <inlineHelpText>(fixed throughout life of contract)</inlineHelpText>
        <label>Monthly Lease Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Allotted_Hours__c</fullName>
        <inlineHelpText>Total hours on contract including carry-over for the entire contract period (e.g. 5 years)</inlineHelpText>
        <label>Total Allotted Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Year__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Hours_Allotted__c</fullName>
        <inlineHelpText>Allotted hours for this program year</inlineHelpText>
        <label>Annual Hours Allotted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Program Year</relationshipLabel>
        <relationshipName>CO_Client_Program_Year</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <label>Client Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipName>Client_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Program Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Leg__c.object
<CustomObject>
    <description>This is used for flight legs.</description>
    <fields>
        <fullName>Actual_Flight_Time_hours__c</fullName>
        <label>Actual Flight Time (hours)</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions (Business Account)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Period</label>
        <referenceTo>Client_Program_Year__c</referenceTo>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Client_Program__c.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trip_Manager_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trip Manager Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Leg</fullName>
        <active>true</active>
        <label>Leg</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Aircraft_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aerospatiale AS 350B</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS 355F2</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS365 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale EC155</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta 109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta A109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta SPA AB139</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 318</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 319</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-200</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-300</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SP</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SPX</fullName>
    </customValue>
    <customValue>
        <fullName>Beechjet 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 429</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 430</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-400</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-600</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-700</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-800</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-900</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 747SP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 777-200</fullName>
    </customValue>
    <customValue>
        <fullName>Phenom 300</fullName>
    </customValue>
    <masterLabel>Aircraft Type</masterLabel>
</GlobalValueSet>

src/classes/UpgradeDowngradeCalculatorTest.cls
@isTest
public class UpgradeDowngradeCalculatorTest {
    
	@isTest
    public static void Test1(){
        
		// Data setup
		Account ac = new Account();
        ac.Name = 'Flexjet, LLC'; 
		insert ac;
        
        Operator_Program__c op = new Operator_Program__c();
        op.Operator__c = ac.Id;
        op.Program_Status__c = 'Available';
        insert op;
        
        Client_Program__c cp = new Client_Program__c();
        cp.Account__c = ac.Id;
        cp.Operator_Program__c = op.Id;
        cp.Client_Program_Status__c = 'Active';
        cp.Current_MMF__c = 100;
        cp.Monthly_Lease_Fee__c = 100;
        cp.Total_Allotted_Hours__c = 100;
        cp.Current_OHF__c = 100;
        cp.Latest_Fuel__c = 100;
        cp.Contracted_Aircraft_Type__c = 'Phenom 300';
        insert cp;

        Client_Program_Year__c cpp = new Client_Program_Year__c();
        cpp.Client_Program__c = cp.Id;
        cpp.Business_Account__c = ac.Id;
        cpp.Annual_Hours_Allotted__c = 5;
        insert cpp;
        
        Case tm = new Case();
        tm.AccountId = ac.Id;
        insert tm;
        
        Leg__c l = new Leg__c();
        l.RecordTypeId = Schema.SObjectType.Leg__c.getRecordTypeInfosByDeveloperName().get('Leg').getRecordTypeId();
        l.Client_Program__c = cp.Id;
        l.Client_Program_Year__c = cpp.Id;
        l.Trip_Manager_Number__c = tm.Id;
        l.Actual_Flight_Time_hours__c = 3;
        insert l;
        
		// Run the code
        Test.startTest();
		UpgradeDowngradeCalculatorCmp ctrl = new UpgradeDowngradeCalculatorCmp();
        ctrl.programPeriodIdX = cpp.Id;
        ctrl.BilledHours = 3;
        decimal allInCost = ctrl.AllInCost;
        try {
            ctrl.legIdX = l.Id;
        } catch (Exception ex) {}
        Test.stopTest();
        
        // Verify Results
        System.assertEquals(2040, allInCost);
    }
}