src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Membership_Fee__c</fullName>
        <label>Annual Membership Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grand_Total_Billed_Hours__c</fullName>
        <inlineHelpText>All billed hours minus any hours credits</inlineHelpText>
        <label>Grand Total Billed Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MembershipFeeCalculator.cls
public class MembershipFeeCalculator {

    public Client_Program__c program { get; set; }
    
    public decimal membershipFeePerHour {
        get {
            if (program.Annual_Membership_Fee__c == null)
                return 0;
            if (program.Grand_Total_Billed_Hours__c == null)
                return 0;
            return program.Annual_Membership_Fee__c / program.Grand_Total_Billed_Hours__c;
        }
    }
    
    public MembershipFeeCalculator(ApexPages.StandardController ctrl) {
        program = [SELECT Id, Name, Annual_Membership_Fee__c, Grand_Total_Billed_Hours__c FROM Client_Program__c WHERE Id = :ctrl.getId()];
    }
}