src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Current_Fair_Market_Value__c</fullName>
        <inlineHelpText>(does not include remarketing fee)</inlineHelpText>
        <label>Current Fair Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Depreciated_Value__c</fullName>
        <formula>Initial_Asset_Value__c - Current_Fair_Market_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Depreciated Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Depreciation__c</fullName>
        <label>Estimated Depreciation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Initial_Asset_Value__c</fullName>
        <inlineHelpText>(Including Security Deposit)</inlineHelpText>
        <label>Initial Asset Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Cost__c</fullName>
        <inlineHelpText>Percentage supplied by client.</inlineHelpText>
        <label>Opportunity Cost %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Flown_Hours__c</fullName>
        <label>Grand Total Flown Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Year__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Hours_Allotted__c</fullName>
        <inlineHelpText>Allotted hours for this program year</inlineHelpText>
        <label>Annual Hours Allotted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <label>Client Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipName>Client_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Year__c</fullName>
        <label>Program Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Flown_Hours__c</fullName>
        <inlineHelpText>Total reconciled and flown hours</inlineHelpText>
        <label>Total Flown Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Program Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DepreciationCalculator.cls
public class DepreciationCalculator {

    public Client_Program__c program { get; set; }
    public Client_Program_Year__c currentPeriod { get; set; }
    
    public integer daysIntoProgramYear {
        get {
            if (currentPeriod == null || currentPeriod.Start_Date__c == null) return 0;
            return currentPeriod.Start_Date__c.daysBetween(Date.today());
        }
    }
    
    public decimal percentageIntoProgramPeriod {
        get {
            return daysIntoProgramYear * 100.0 / 365;
        }
    }
    
    public decimal depreciationPerHour1 {
        get {
            if (program.Initial_Asset_Value__c == null) return 0;
            if (program.Estimated_Depreciation__c == null) return 0;
            if (currentPeriod == null || currentPeriod.Annual_Hours_Allotted__c == null) return 0;
            return program.Initial_Asset_Value__c * program.Estimated_Depreciation__c / (currentPeriod.Annual_Hours_Allotted__c * 100);
        }
    }
    
    public decimal depreciationPerHour2 {
        get {
            if (program.Depreciated_Value__c == null) return 0;
            if (program.Total_Flown_Hours__c == null) return 0;
            return program.Depreciated_Value__c / program.Total_Flown_Hours__c;
        }
    }
    
    public decimal costOfCapital1 {
        get {
            if (program.Initial_Asset_Value__c == null) return 0;
            if (program.Opportunity_Cost__c == null) return 0;
            if (currentPeriod == null || currentPeriod.Annual_Hours_Allotted__c == null) return 0;
            return program.Initial_Asset_Value__c * program.Opportunity_Cost__c / (currentPeriod.Annual_Hours_Allotted__c * 100);
        }
    }
    
    public decimal costOfCapital2 {
        get {
            if (currentPeriod == null || currentPeriod.Annual_Hours_Allotted__c == null) return 0;
            return daysIntoProgramYear * currentPerDay * 100 / (currentPeriod.Annual_Hours_Allotted__c * percentageIntoProgramPeriod);
        }
    }
    
    public decimal currentPerDay { get; set; }
    
    public List<CapitalYearWrapper> years { get; set; }
    
    public DepreciationCalculator(ApexPages.StandardController ctrl) {
    
        program = [SELECT Id, Name, Initial_Asset_Value__c, Current_Fair_Market_Value__c, Depreciated_Value__c, Total_Flown_Hours__c, Estimated_Depreciation__c, Opportunity_Cost__c,
                   		(SELECT Id, Name, Start_Date__c, End_Date__c, Program_Year__c, Annual_Hours_Allotted__c FROM Client_Program_Years__r ORDER BY Start_Date__c ASC) 
                   FROM Client_Program__c WHERE Id = :ctrl.getId()];
        
        currentPerDay = 0;
        
        if (program.Client_Program_Years__r.size() > 0) {
            Date cDate = Date.today();
            
            for (Client_Program_Year__c period : program.Client_Program_Years__r) {
                if (period.Start_Date__c <= cDate && period.End_Date__c > cDate) {
                    currentPeriod = period;
                }
            }
            if (currentPeriod == null) {
                if (program.Client_Program_Years__r[0].Start_Date__c > cDate)
                    currentPeriod = program.Client_Program_Years__r[0];
                if (program.Client_Program_Years__r[program.Client_Program_Years__r.size() - 1].End_Date__c < cDate)
                    currentPeriod = program.Client_Program_Years__r[program.Client_Program_Years__r.size() - 1];
            }
            
            
            years = new List<CapitalYearWrapper>();
            decimal yearly = program.Initial_Asset_Value__c == null ? 0 : program.Initial_Asset_Value__c;
            for (Client_Program_Year__c period : program.Client_Program_Years__r) {
                CapitalYearWrapper cyw = new CapitalYearWrapper();
                if (program.Opportunity_Cost__c != null)
                	cyw.total = yearly * program.Opportunity_Cost__c / 100;
                if (currentPeriod.Annual_Hours_Allotted__c != null)
                	cyw.perHour = cyw.total / currentPeriod.Annual_Hours_Allotted__c;
                cyw.perDay = cyw.total / 365;
                
                yearly += cyw.total;
                
                if (period == currentPeriod) {
                    currentPerDay = cyw.perDay;
                }
                
                years.add(cyw);
            }
        }
        
    }
    
    public class CapitalYearWrapper {
        public decimal total { get; set; }
        public decimal perHour { get; set; }
        public decimal perDay { get; set; }
        
        public CapitalYearWrapper() {
            total = 0;
            perHour = 0;
            perDay = 0;
        }
    }
    
}