src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Annual_Membership_Fee__c</fullName>
        <label>Annual Membership Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Program_Status__c</fullName>
        <label>Client Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Fair_Market_Value__c</fullName>
        <inlineHelpText>(does not include remarketing fee)</inlineHelpText>
        <label>Current Fair Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Depreciation__c</fullName>
        <label>Estimated Depreciation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Grand_Total_Billed_Hours__c</fullName>
        <inlineHelpText>All billed hours minus any hours credits</inlineHelpText>
        <label>Grand Total Billed Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Initial_Asset_Value__c</fullName>
        <inlineHelpText>(Including Security Deposit)</inlineHelpText>
        <label>Initial Asset Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Cost__c</fullName>
        <inlineHelpText>Percentage supplied by client.</inlineHelpText>
        <label>Opportunity Cost %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Flown_Hours__c</fullName>
        <label>Grand Total Flown Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Year__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Hours_Allotted__c</fullName>
        <inlineHelpText>Allotted hours for this program year</inlineHelpText>
        <label>Annual Hours Allotted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <label>Client Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipName>Client_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Flown_Hours__c</fullName>
        <inlineHelpText>Total reconciled and flown hours</inlineHelpText>
        <label>Total Flown Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Program Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DepreciationCalculatorTest.cls
@isTest
public class DepreciationCalculatorTest {

    @isTest
	public static void Test1() {
		
		// Data setup
		Account acc = new Account();
        acc.Name = 'Test298762';
        insert acc;
        
        Operator_Program__c op = new Operator_Program__c();
        op.Name = 'Test893723';
        op.Operator__c = acc.Id;
        op.Program_Status__c = 'Available';
        insert op;
        
        Client_Program__c p = new Client_Program__c();
        p.Account__c = acc.Id;
        p.Annual_Membership_Fee__c = 10000;
        p.Grand_Total_Billed_Hours__c = 100;
        p.Operator_Program__c = op.Id;
        p.Client_Program_Status__c = 'Active';
        p.Initial_Asset_Value__c = 1000000;
        p.Estimated_Depreciation__c = 10;
        p.Current_Fair_Market_Value__c = 900000;
        p.Total_Flown_Hours__c = 100;
        p.Opportunity_Cost__c = 5;
        insert p;
        
        Client_Program_Year__c py = new Client_Program_Year__c();
        py.Client_Program__c = p.Id;
        py.Start_Date__c = Date.newInstance(Date.today().year(), 1, 1);
        py.End_Date__c = Date.newInstance(Date.today().year(), 12, 31);
        py.Annual_Hours_Allotted__c = 100;
        insert py;
		
		// Run the code
		Test.startTest();
		DepreciationCalculator ctrl = new DepreciationCalculator(new ApexPages.StandardController(p));
        integer daysIntoProgramYear = ctrl.daysIntoProgramYear;
        decimal percentageIntoProgramPeriod = ctrl.daysIntoProgramYear;    
		decimal depreciationPerHour1 = ctrl.depreciationPerHour1;
        decimal depreciationPerHour2 = ctrl.depreciationPerHour2;
        decimal costOfCapital1 = ctrl.costOfCapital1;
        decimal costOfCapital2 = ctrl.costOfCapital2;        
		Test.stopTest();
		
		// Verify Results
		//TO-DO: Values should be dynamic based on current date since they change as year progresses
		/*
		System.assertEquals(260, ctrl.daysIntoProgramYear); 
		System.assertEquals(65, Math.round(ctrl.percentageIntoProgramPeriod));
		System.assertEquals(1000, ctrl.depreciationPerHour1);
		System.assertEquals(1000, ctrl.depreciationPerHour2);
		System.assertEquals(500, ctrl.costOfCapital1);
		System.assertEquals(500, Math.round(ctrl.costOfCapital2));
		*/
	}
    
}