src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Contracted_Aircraft_Type__c</fullName>
        <label>Contracted Aircraft Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Conversion_Override__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Conversion Overrides</relationshipLabel>
        <relationshipName>Client_Program_Conversion_Overrides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client Program Conversion Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Program Conversion Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Conversion_Table__mdt.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flexjet, LLC</fullName>
                    <default>true</default>
                    <label>Flexjet, LLC</label>
                </value>
                <value>
                    <fullName>NetJets Aviation</fullName>
                </value>
                <value>
                    <fullName>NetJets Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Plane__c</fullName>
        <label>From Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Conversion Table</label>
    <pluralLabel>Conversion Table</pluralLabel>
</CustomObject>

src/objects/Leg__c.object
<CustomObject>
    <description>This is used for flight legs.</description>
    <fields>
        <fullName>Aircraft_Requested__c</fullName>
        <label>Aircraft Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Client_Program__c.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Flight_Time_hours__c</fullName>
        <label>Estimated Billable Time</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Estimated_Billable_Time__c</fullName>
        <inlineHelpText>This is the estimated billable time per trip sheet.  (Interchange ratio NOT applied)</inlineHelpText>
        <label>Original Estimated Billable Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Aircraft_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aerospatiale AS 350B</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS 355F2</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS365 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale EC155</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta 109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta A109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta SPA AB139</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 318</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 319</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-200</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-300</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SP</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SPX</fullName>
    </customValue>
    <customValue>
        <fullName>Beechjet 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 429</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 430</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-400</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-600</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-700</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-800</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-900</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 747SP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 777-200</fullName>
    </customValue>
    <masterLabel>Aircraft Type</masterLabel>
</GlobalValueSet>

src/classes/LegHandler.cls
public class LegHandler {

    public static void SetEstimatedFlightTimeHours(List<Leg__c> newList) {

        // Gather data for conversion table
        Set<Id> programIds = new Set<Id>();
        Set<String> companies = new Set<String>();
        Set<String> fromPlanes = new Set<String>();
        Set<String> toPlanes = new Set<String>();
        for (Leg__c l : newList) {
            if (!String.isEmpty(l.Aircraft_Requested__c)) {
                toPlanes.add(l.Aircraft_Requested__c);
            }
            if (l.Client_Program__c != null) {
            	programIds.add(l.Client_Program__c);
            }
        }
        
        Map<Id, Map<string, decimal>> conversionRates = new Map<Id, Map<string, decimal>>(); // Program Id -> To Plane -> Rate
        Map<Id, Client_Program__c> programMap = new Map<Id, Client_Program__c>();
        
        if (programIds.size() > 0) {
            programMap = new Map<Id, Client_Program__c>([SELECT Id, Contracted_Aircraft_Type__c, Operator_Program__r.Operator__r.Name,
                                                         		(SELECT To_Plane__c, Exchange_Rate__c FROM Client_Program_Conversion_Overrides__r)
                                                         FROM Client_Program__c WHERE Id IN :programIds AND Contracted_Aircraft_Type__c != null]);
            for (Client_Program__c program : programMap.values()) {
                if (!String.isEmpty(program.Contracted_Aircraft_Type__c)) {
                    fromPlanes.add(program.Contracted_Aircraft_Type__c);
                }
                if (!String.isEmpty(program.Operator_Program__r.Operator__r.Name)) {
                    companies.add(program.Operator_Program__r.Operator__r.Name);
                }
                
                conversionRates.put(program.Id, new Map<string, decimal>());
                for (Client_Program_Conversion_Override__c cpco : program.Client_Program_Conversion_Overrides__r) {
                    conversionRates.get(program.Id).put(cpco.To_Plane__c, cpco.Exchange_Rate__c);
                }
            }
        }
        
        if (fromPlanes.size() > 0 && toPlanes.size() > 0) {
            for (Conversion_Table__mdt ct : [SELECT Company__c, From_Plane__c, To_Plane__c, Exchange_Rate__c
                                                 FROM Conversion_Table__mdt 
                                                 WHERE Company__c IN :companies AND From_Plane__c IN :fromPlanes AND To_Plane__c IN :toPlanes])
        	{
                for (Id programId : programMap.keySet()) {
                    if (!conversionRates.containsKey(programId))
                        conversionRates.put(programId, new Map<String, decimal>());
                    if (programMap.get(programId).Operator_Program__r.Operator__r.Name == ct.Company__c) {
                        if (!conversionRates.get(programId).containsKey(ct.To_Plane__c)) {
                            conversionRates.get(programId).put(ct.To_Plane__c, ct.Exchange_Rate__c);
                        }
                    }
                }
            }
            
            // Set the estimated flight time hours
            for (Leg__c l : newList) {
                if (!String.isEmpty(l.Aircraft_Requested__c) && l.Estimated_Flight_Time_hours__c == NULL ) {
                    if (l.Client_Program__c != null) {
                        if (conversionRates.containsKey(l.Client_Program__c)) {
                            if (conversionRates.get(l.Client_Program__c).containsKey(l.Aircraft_Requested__c)) {
                                l.Estimated_Flight_Time_hours__c = (l.Original_Estimated_Billable_Time__c == null ? 0 : l.Original_Estimated_Billable_Time__c) * conversionRates.get(l.Client_Program__c).get(l.Aircraft_Requested__c);
                            }
                        }
                    }
                }
            }
        }
    }
    
}