src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Contracted_Aircraft_Type__c</fullName>
        <label>Contracted Aircraft Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Conversion_Override__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Conversion Overrides</relationshipLabel>
        <relationshipName>Client_Program_Conversion_Overrides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Program Conversion Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Program Conversion Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plane_for_Company__mdt.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flexjet, LLC</fullName>
                    <default>true</default>
                    <label>Flexjet, LLC</label>
                </value>
                <value>
                    <fullName>NetJets Aviation</fullName>
                </value>
                <value>
                    <fullName>NetJets Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plane__c</fullName>
        <label>Plane</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Plane for Company</label>
    <pluralLabel>Planes for Company</pluralLabel>
</CustomObject>

src/globalValueSets/Aircraft_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aerospatiale AS 350B</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS 355F2</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS365 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale EC155</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta 109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta A109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta SPA AB139</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 318</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 319</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-200</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-300</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SP</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SPX</fullName>
    </customValue>
    <customValue>
        <fullName>Beechjet 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 429</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 430</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-400</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-600</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-700</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-800</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-900</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 747SP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 777-200</fullName>
    </customValue>
    <masterLabel>Aircraft Type</masterLabel>
</GlobalValueSet>

src/classes/EditOverrides.cls
public with sharing class EditOverrides {
    
    public boolean hasError { get; set; }
    public string fromPlane { get; set; }

    public List<SelectOption> options { get; set; }

    public EditOverrides(ApexPages.StandardController ctrl) {

        hasError = false;

        Client_Program_Conversion_Override__c record = (Client_Program_Conversion_Override__c)ctrl.getRecord();
        if (record.Program__c == null) {
            hasError = true;
            return;
        }

        Client_Program__c cp = [SELECT Contracted_Aircraft_Type__c, Operator_Program__r.Operator__r.Name FROM Client_Program__c WHERE Id = :record.Program__c];
        fromPlane = cp.Contracted_Aircraft_Type__c;

        options = new List<SelectOption>();
        for (Plane_for_Company__mdt mdt : [SELECT Plane__c FROM Plane_for_Company__mdt WHERE Company__c = :cp.Operator_Program__r.Operator__r.Name]) {
            options.add(new SelectOption(mdt.Plane__c, mdt.Plane__c));
        }
        options.sort();
    }

}