src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Hours_Contracted__c</fullName>
        <inlineHelpText>(before carry-over)</inlineHelpText>
        <label>Annual Hours Contracted</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contracted_Aircraft_Type__c</fullName>
        <label>Contracted Aircraft Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_MMF__c</fullName>
        <inlineHelpText>Grabbing the MMF from the last reconciled MMF transaction</inlineHelpText>
        <label>Current MMF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_OHF__c</fullName>
        <inlineHelpText>Grabbing the OHF from the latest reconciled leg that was not an up/downgrade</inlineHelpText>
        <label>Current OHF</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Latest_Fuel__c</fullName>
        <inlineHelpText>Grabbing latest fuel from latest reconciled transaction that was not up/downgraded</inlineHelpText>
        <label>Latest Fuel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Lease_Fee__c</fullName>
        <inlineHelpText>(fixed throughout life of contract)</inlineHelpText>
        <label>Monthly Lease Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Allotted_Hours__c</fullName>
        <inlineHelpText>Total hours on contract including carry-over for the entire contract period (e.g. 5 years)</inlineHelpText>
        <label>Total Allotted Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Conversion_Override__c.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Combine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Combine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Conversion Overrides</relationshipLabel>
        <relationshipName>Client_Program_Conversion_Overrides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client Program Conversion Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Program Conversion Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Program_Year__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Hours_Allotted__c</fullName>
        <inlineHelpText>Allotted hours for this program year</inlineHelpText>
        <label>Annual Hours Allotted</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <label>Client Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipName>Client_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program Period</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Program Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Conversion_Table__mdt.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flexjet, LLC</fullName>
                    <default>true</default>
                    <label>Flexjet, LLC</label>
                </value>
                <value>
                    <fullName>NetJets Aviation</fullName>
                </value>
                <value>
                    <fullName>NetJets Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Combine__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Combine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Plane__c</fullName>
        <label>From Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Conversion Table</label>
    <pluralLabel>Conversion Table</pluralLabel>
</CustomObject>

src/objects/Leg__c.object
<CustomObject>
    <description>This is used for flight legs.</description>
    <fields>
        <fullName>Client_Program_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Period</label>
        <referenceTo>Client_Program_Year__c</referenceTo>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Client_Program__c.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Estimated_Billable_Time__c</fullName>
        <inlineHelpText>This is the estimated billable time per trip sheet.  (Interchange ratio NOT applied)</inlineHelpText>
        <label>Original Estimated Billable Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Leg</fullName>
        <active>true</active>
        <label>Leg</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Aircraft_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aerospatiale AS 350B</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS 355F2</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS365 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale EC155</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta 109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta A109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta SPA AB139</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 318</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 319</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-200</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-300</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SP</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SPX</fullName>
    </customValue>
    <customValue>
        <fullName>Beechjet 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 429</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 430</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-400</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-600</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-700</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-800</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-900</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 747SP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 777-200</fullName>
    </customValue>
    <masterLabel>Aircraft Type</masterLabel>
</GlobalValueSet>

src/classes/UpgradeDowngradeCalculatorCmp.cls
public class UpgradeDowngradeCalculatorCmp {

    public Id programPeriodIdP { get; set; }
    public Id programPeriodIdX {
        get {
            return programPeriodIdP;
        }
        set {
            if (programPeriodIdP != null) return; // Avoid reloading the page when a change occurs
            programPeriodIdP = value;
            if (programPeriodIdP != null) {
                programPeriod = [SELECT Id, Annual_Hours_Allotted__c,
                                Client_Program__r.Operator_Program__r.Operator__r.Name, Client_Program__r.Annual_Hours_Contracted__c,
                                Client_Program__r.Current_MMF__c, Client_Program__r.Monthly_Lease_Fee__c, Client_Program__r.Total_Allotted_Hours__c,
                                Client_Program__r.Current_OHF__c, Client_Program__r.Latest_Fuel__c, Client_Program__r.Contracted_Aircraft_Type__c
                    FROM Client_Program_Year__c WHERE Id = :programPeriodIdP];

                program = programPeriod.Client_Program__r;

                BilledHours = 0;
                BilledHoursEditable = true;
                
                OwnedHoursSelection = 'Annual Hours Allotted';

                BuildConversionTable();
            }
        }
    }
    public Id legIdP { get; set; }
    public Id legIdX {
        get {
            return legIdP;
        }
        set {
            if (legIdP != null) return; // Avoid reloading the page when a change occurs
            legIdP = value;
            if (legIdP != null) {
                Leg__c leg = [SELECT Id, Original_Estimated_Billable_Time__c, Client_Program__r.Operator_Program__r.Operator__r.Name,
                                Client_Program__r.Current_MMF__c, Client_Program__r.Monthly_Lease_Fee__c, Client_Program__r.Total_Allotted_Hours__c,
                                Client_Program__r.Current_OHF__c, Client_Program__r.Latest_Fuel__c, Client_Program__r.Contracted_Aircraft_Type__c,
                                Client_Program_Year__r.Annual_Hours_Allotted__c, Client_Program__r.Annual_Hours_Contracted__c
                    FROM Leg__c WHERE Id = :legIdP];

                program = leg.Client_Program__r;
                programPeriod = leg.Client_Program_Year__r;

                BilledHours = leg.Original_Estimated_Billable_Time__c  == null ? 0 : leg.Original_Estimated_Billable_Time__c;
                BilledHoursEditable = false;

                OwnedHoursSelection = 'Annual Hours Allotted';

                BuildConversionTable();
            }
        }
    }
    
    public Client_Program__c program { get; set; }
    public Client_Program_Year__c programPeriod { get; set; }
    
    public decimal Monthly { 
        get { 
            return (program.Current_MMF__c == null ? 0 : program.Current_MMF__c) + 
                   (program.Monthly_Lease_Fee__c == null ? 0 : program.Monthly_Lease_Fee__c);
        } 
    }
    public decimal Yearly { get { return Monthly * 12; } }
    public string OwnedHoursSelection { get; set; }
    public decimal OwnedHours {
        get {
            if (OwnedHoursSelection == 'Annual Hours Allotted') {
                return programPeriod.Annual_Hours_Allotted__c;
            } else {
                return program.Annual_Hours_Contracted__c;
            }
        }
    }
    public decimal FixedPerHour { 
        get {
            if (OwnedHours == null || OwnedHours == 0)
                return 0;
            return Yearly / OwnedHours;
        }
    }
    public decimal Variable { 
        get { 
            return (program.Current_OHF__c == null ? 0 : program.Current_OHF__c) + 
                   (program.Latest_Fuel__c == null ? 0 : program.Latest_Fuel__c);
        } 
    }
    public decimal AllIn { get { return FixedPerHour + Variable; } }
    public decimal BilledHours { get; set; }
    public boolean BilledHoursEditable { get; set; }
    public decimal VariableCost { get { return Variable * BilledHours; } }
    public decimal AllInCost { get { return AllIn * BilledHours; } }
    
    // Conversion table
    public List<ConversionTableRow> ConversionTable { get; set; }
    public boolean HasConversionData { get { return ConversionTable != null && ConversionTable.size() > 0; } }
    
    public void BuildConversionTable() {
        Set<String> overridedPlanes = new Set<String>();
        Map<decimal, ConversionTableRow> tempGroupingMap = new Map<decimal, ConversionTableRow>();
        
        for (Client_Program_Conversion_Override__c ct : [SELECT To_Plane__c, Exchange_Rate__c, Do_Not_Combine__c FROM Client_Program_Conversion_Override__c 
                                                          	WHERE Program__c = :program.Id])
        {
            overridedPlanes.add(ct.To_Plane__c);
            
            if (ct.Do_Not_Combine__c == true) {
                tempGroupingMap.put(ct.Exchange_Rate__c + 1000, new ConversionTableRow(ct.To_Plane__c, ct.Exchange_Rate__c, BilledHours, AllIn, AllInCost, VariableCost));
            } else {
                if (tempGroupingMap.containsKey(ct.Exchange_Rate__c)) {
                    tempGroupingMap.get(ct.Exchange_Rate__c).title += ' <br /> ' + ct.To_Plane__c;
                } else {
                    tempGroupingMap.put(ct.Exchange_Rate__c, new ConversionTableRow(ct.To_Plane__c, ct.Exchange_Rate__c, BilledHours, AllIn, AllInCost, VariableCost));
                }
            }
        }
        
        for (Conversion_Table__mdt ct : [SELECT From_Plane__c, To_Plane__c, Exchange_Rate__c, Do_Not_Combine__c
                                         FROM Conversion_Table__mdt 
                                         WHERE Company__c = :program.Operator_Program__r.Operator__r.Name 
                                         	AND From_Plane__c = :program.Contracted_Aircraft_Type__c])
        {
            if (!overridedPlanes.contains(ct.To_Plane__c)) {
                if (ct.Do_Not_Combine__c == true) {
                    tempGroupingMap.put(ct.Exchange_Rate__c + 1000, new ConversionTableRow(ct.To_Plane__c, ct.Exchange_Rate__c, BilledHours, AllIn, AllInCost, VariableCost));
                } else {
                    if (tempGroupingMap.containsKey(ct.Exchange_Rate__c)) {
                        tempGroupingMap.get(ct.Exchange_Rate__c).title += ' <br /> ' + ct.To_Plane__c;
                    } else {
                        tempGroupingMap.put(ct.Exchange_Rate__c, new ConversionTableRow(ct.To_Plane__c, ct.Exchange_Rate__c, BilledHours, AllIn, AllInCost, VariableCost));
                    }
                }
            }
        }
        
        ConversionTable = tempGroupingMap.values();
        ConversionTable.sort();
    }

    public PageReference cancel() {
        if (legIdX != null)
            return new PageReference('/' + legIdX);
        if (programPeriodIdX != null)
            return new PageReference('/' + programPeriodIdX);
        return null;
    }
    
    public class ConversionTableRow implements Comparable {
        public string title { get; set; }
        public decimal rate { get; set; }
        public decimal hours { get; set; }
        public decimal hoursSavings { get; set; }
        public decimal varCost { get; set; }
        public decimal varSavings { get; set; }
        public decimal cost { get; set; }
        public decimal savings { get; set; }
        
        public ConversionTableRow(string title, decimal rate, decimal billedHours, decimal allIn, decimal allInCost, decimal variableCost) {
            this.title = title;
            this.rate = rate;
            this.hours = Math.round(rate * billedHours * 10) / 10.0;
            this.hoursSavings = billedHours - this.hours;
            this.varCost = this.rate * variableCost;
            this.varSavings = variableCost - this.varCost;
            this.cost = this.hours * allIn;
            this.savings = allInCost - this.cost;
        }
        
        public Integer compareTo(Object compareTo) {
            ConversionTableRow compTo = (ConversionTableRow)compareTo;
            if (this.rate < compTo.rate)
                return -1;
            if (this.rate > compTo.rate)
                return 1;
            return 0;
        }
    }

}