src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Client_Program_Status__c</fullName>
        <label>Client Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contracted_Aircraft_Type__c</fullName>
        <label>Contracted Aircraft Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Program_Conversion_Override__c.object
<CustomObject>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Conversion Overrides</relationshipLabel>
        <relationshipName>Client_Program_Conversion_Overrides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client Program Conversion Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Program Conversion Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Conversion_Table__mdt.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flexjet, LLC</fullName>
                    <default>true</default>
                    <label>Flexjet, LLC</label>
                </value>
                <value>
                    <fullName>NetJets Aviation</fullName>
                </value>
                <value>
                    <fullName>NetJets Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Plane__c</fullName>
        <label>From Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Plane__c</fullName>
        <label>To Plane</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Conversion Table</label>
    <pluralLabel>Conversion Table</pluralLabel>
</CustomObject>

src/objects/Leg__c.object
<CustomObject>
    <description>This is used for flight legs.</description>
    <fields>
        <fullName>Aircraft_Requested__c</fullName>
        <label>Aircraft Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Aircraft_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Client_Program__c.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Client_Program__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Flight_Time_hours__c</fullName>
        <label>Estimated Billable Time</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Estimated_Billable_Time__c</fullName>
        <inlineHelpText>This is the estimated billable time per trip sheet.  (Interchange ratio NOT applied)</inlineHelpText>
        <label>Original Estimated Billable Time</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trip_Manager_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trip Manager Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Leg</fullName>
        <active>true</active>
        <label>Leg</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Aircraft_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Aerospatiale AS 350B</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS 355F2</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale AS365 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospatiale EC155</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta 109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta A109</fullName>
    </customValue>
    <customValue>
        <fullName>Agusta SPA AB139</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 318</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 319</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-200</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 340-300</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus 355 Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SP</fullName>
    </customValue>
    <customValue>
        <fullName>Astra SPX</fullName>
    </customValue>
    <customValue>
        <fullName>Beechjet 400A</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 429</fullName>
    </customValue>
    <customValue>
        <fullName>Bell 430</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-400</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-600</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-700</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-800</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 737-900</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 747SP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-200VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 767-300</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing 777-200</fullName>
    </customValue>
    <customValue>
        <fullName>Challenger 650</fullName>
    </customValue>
    <customValue>
        <fullName>Citation X</fullName>
    </customValue>
    <masterLabel>Aircraft Type</masterLabel>
</GlobalValueSet>

src/classes/LegTriggerTest.cls
@isTest
public class LegTriggerTest {

    @isTest
	public static void Test_SetEstimatedFlightTimeHours1() {
		
		// Data setup
		Account ac = new Account();
        ac.Name = 'NetJets Aviation'; 
		insert ac;
        
        Operator_Program__c op = new Operator_Program__c();
        op.Operator__c = ac.Id;
        op.Program_Status__c = 'Available';
        insert op;
        
		Client_Program__c cp = new Client_Program__c();
        cp.Client_Program_Status__c = 'Active';
        cp.Contracted_Aircraft_Type__c = 'Challenger 650';
        cp.Operator_Program__c = op.Id;
        insert cp;
        
        Case tm = new Case();
        tm.AccountId = ac.Id;
        insert tm;
		
		// Run the code
		Test.startTest();
		
        Leg__c l = new Leg__c();
        l.RecordTypeId = Schema.SObjectType.Leg__c.getRecordTypeInfosByDeveloperName().get('Leg').getRecordTypeId();
        l.Client_Program__c = cp.Id;
        l.Trip_Manager_Number__c = tm.Id;
        l.Aircraft_Requested__c = 'Citation X';
        l.Original_Estimated_Billable_Time__c = 100;
        insert l;
        
		Test.stopTest();
		
		// Verify Results
		Conversion_Table__mdt ct = [SELECT Exchange_Rate__c FROM Conversion_Table__mdt 
                                       WHERE Company__c = 'NetJets Aviation' AND From_Plane__c = 'Challenger 650' AND To_Plane__c = 'Citation X'];
        l = [SELECT Estimated_Flight_Time_hours__c FROM Leg__c WHERE Id = :l.Id];
        System.assertEquals(100 * ct.Exchange_Rate__c, l.Estimated_Flight_Time_hours__c);
	}
    
    @isTest
	public static void Test_SetEstimatedFlightTimeHours2() {
		
		// Data setup
		Account ac = new Account();
        ac.Name = 'NetJets Aviation'; 
		insert ac;
        
        Operator_Program__c op = new Operator_Program__c();
        op.Operator__c = ac.Id;
        op.Program_Status__c = 'Available';
        insert op;
        
		Client_Program__c cp = new Client_Program__c();
        cp.Client_Program_Status__c = 'Active';
        cp.Contracted_Aircraft_Type__c = 'Challenger 650';
        cp.Operator_Program__c = op.Id;
        insert cp;
        
        Client_Program_Conversion_Override__c cpco = new Client_Program_Conversion_Override__c();
        cpco.Program__c = cp.Id;
        cpco.To_Plane__c = 'Citation X';
        cpco.Exchange_Rate__c = 0.77;
        insert cpco;
        
        Case tm = new Case();
        tm.AccountId = ac.Id;
        insert tm;
		
		// Run the code
		Test.startTest();
		
        Leg__c l = new Leg__c();
        l.RecordTypeId = Schema.SObjectType.Leg__c.getRecordTypeInfosByDeveloperName().get('Leg').getRecordTypeId();
        l.Client_Program__c = cp.Id;
        l.Trip_Manager_Number__c = tm.Id;
        l.Aircraft_Requested__c = 'Citation X';
        l.Original_Estimated_Billable_Time__c = 100;
        insert l;
        
		Test.stopTest();
		
		// Verify Results
		l = [SELECT Estimated_Flight_Time_hours__c FROM Leg__c WHERE Id = :l.Id];
        System.assertEquals(77, l.Estimated_Flight_Time_hours__c);
	}

}