src/objects/Client_Program__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Membership_Fee__c</fullName>
        <label>Annual Membership Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Program_Status__c</fullName>
        <label>Client Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grand_Total_Billed_Hours__c</fullName>
        <inlineHelpText>All billed hours minus any hours credits</inlineHelpText>
        <label>Grand Total Billed Hours</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operator_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operator Program</label>
        <referenceTo>Operator_Program__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Client_Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Contract ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Operator_Program__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operator Programs</relationshipLabel>
        <relationshipName>Operator_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operator Program</label>
    <nameField>
        <label>Operator Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operator Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MembershipFeeCalculatorTest.cls
@isTest
public class MembershipFeeCalculatorTest {

    @isTest
	public static void Test1() {
		
		// Data setup
		Account acc = new Account();
        acc.Name = 'Test298762';
        insert acc;
        
        Operator_Program__c op = new Operator_Program__c();
        op.Name = 'Test893723';
        op.Operator__c = acc.Id;
        op.Program_Status__c = 'Available';
        insert op;
        
        Client_Program__c p = new Client_Program__c();
        p.Annual_Membership_Fee__c = 10000;
        p.Grand_Total_Billed_Hours__c = 100;
        p.Operator_Program__c = op.Id;
        p.Client_Program_Status__c = 'Active';
        insert p;
		
		// Run the code
		Test.startTest();
		MembershipFeeCalculator ctrl = new MembershipFeeCalculator(new ApexPages.StandardController(p));
        Decimal fee = ctrl.membershipFeePerHour;
		Test.stopTest();
		
		// Verify Results
		System.assertEquals(100, fee);
	}

}